name: Deploy to Cloud Run

on: 
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Verify gcloud authentication
      - name: Verify gcloud authentication
        run: |
          gcloud auth list


      
      - name: Run GCP setup script
        run: bash scripts/setup_gcp.sh
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_REGION: us-central1
          GCP_REPO_NAME: -ci-cd-cloud-run
          GCP_SA_NAME: -github-actions-cloud-run

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & Push Docker image to Artifact Registry
        run: |
          IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/-ci-cd-cloud-run/my-app"
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA
          echo "IMAGE=$IMAGE:$GiTHUB_SHA" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
            --image $IMAGE \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated 
