name: Build and Deploy to Cloud Run

on: 
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # Service account key is stored in GitHub Secrets as GCP_SA_KEY and updated in the repo settings
      - name: Authenticate to Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Gloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      
    # # Verify gcloud authentication
    #   - name: Verify gcloud authentication
    #     run: |
    #       gcloud auth list

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
        

      - name: Build & Push Docker image to Artifact Registry
        run: |
          IMAGE="${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPO_NAME }}/my-app"
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA
          echo "IMAGE=$IMAGE:$GiTHUB_SHA" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
            --image $IMAGE \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated 
